use_frameworks!
source "https://github.com/CocoaPods/Specs.git"
platform :ios, "9.0"

target 'RAC_AFNetWorking' do

pod 'ReactiveObjC'
pod 'AFNetworking'
pod 'MJExtension'
pod 'SDWebImage'


end

 


